---
# tasks file for terraform-state
- name: get state version for workspace {{ workspace }}
  ansible.builtin.uri:
    url: "{{ hostname }}/api/v2/workspaces/{{ workspace }}/current-state-version"
    headers:
      Content-Type: application/vnd.api+json
      Authorization: "Bearer {{ access_token }}"
  register: current_state

- name: get state outputs for state version {{ current_state.data.id }}
  ansible.builtin.uri:
    url: "{{ hostname }}/api/v2/state-versions/{{ current_state.data.id }}/outputs"
    headers:
      Content-Type: application/vnd.api+json
      Authorization: "Bearer {{ access_token }}"
  register: current_state_outputs

- name: set each key/value pair as a separate fact
  ansible.builtin.set_fact:
    "{{ item.attributes.name }}": "{{ item.attributes.value }}"
    state_output_keys: "{{ fact_names | default([]) + [item.attributes.name] }}"
  loop: "{{ current_state_outputs.data }}"

- name: show state outputs
  ansible.builtin.debug:
    msg: "{{ item }} : {{ lookup('vars', item) }}"
  loop: "{{ state_output_keys }}"