---
- name: listen for tfc events
  hosts: all

  sources:
    - name: tfc notifications webhook
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: pending status rule
      condition: event.payload.notifications["run_status"] == "pending"
      action:
        debug:
          msg: "TFC run is pending"

    - name: planning status rule
      condition: event.payload.notifications["run_status"] == "planning"
      action:
        debug:
          msg: "TFC run is planning"

    - name: catchall status rule
      condition: event.payload.notifications[0].run_status not in ["pending", "planning"]
      action:
        print_event:
          pretty: true
