---
- name: listen for tfc pre apply run task events
  hosts: all
  sources:
    - name: tfc run task webhook
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: post plan status rule
      condition: event.payload.stage == "post_plan"
      actions:
        - print_event:
           pretty: true
        - run_job_template:
            name: Run Task Response
            organization: Default
            job_args:
              extra_vars:
                access_token: event.payload.access_token
                task_result_callback_url: event.task_result_callback_url
              