---
- name: listen for tfc pre apply run task events
  hosts: all
  sources:
    - name: tfc run task webhook
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
        hmac_secret: terraformlovesansible!
        hmac_algo: sha256
        hmac_header: "X-Tfc-Task-Signature"
        hmac_format: base64

  rules:
    - name: post plan status rule
      condition: event.payload.stage == "post_plan"
      actions:
        - print_event:
           pretty: true
        - run_job_template:
            name: Run Task Response
            organization: Default
            job_args:
              extra_vars:
              