---
- name: listen for tfc pre apply run task events
  hosts: all
  sources:
    - name: tfc run task webhook
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: pre-apply status rule
      condition: event.payload.stage == "pre_apply"
      actions:
        - print_event:
           pretty: true
        - run_job_template:
            name: Run Task Response
            organization: Default