---
- name: listen for tfc events
  hosts: all

  sources:
    - name: tfc notifications webhook
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
    - name: pending status rule
      condition: event.payload.notifications.run_status == "pending"
      action:
        debug:
          msg: "TFC Run is in a pending state"
