---
- hosts: all
  gather_facts: false
  tasks:
  - name: post plan run tasks
    block:
    - name: output callback details
      ansible.builtin.debug:
        msg: 
        - "{{ access_token }}"
        - "{{ task_result_callback_url }}"

    - name: set passed status fact
      ansible.builtin.set_fact: 
        status: "passed"
        message: "run task completed succesfully"
      # force a change when we get to this block.
      changed_when: true
      notify: send run task response
    rescue:
      - name: make sure handlers run
        meta: flush_handlers

      - name: set failed status fact
        ansible.builtin.set_fact: 
          status: "failed"
          message: "run task execution encountered a problem. check Ansible Automation Platform logs for details"
  handlers:
    - ansible.builtin.import_tasks: handlers/run-task-response-handler.yml
      
    



