---
- hosts: localhost
  connection: local
  gather_facts: true
  roles:
  - role: terraform-state

- hosts: "{{ hostvars['localhost']['public_dns'] | default('host_does_not_exist')}}"
  gather_facts: true
  tasks:
    - name: include tasks to execute against target hosts
      block:    
        - name: include mock-vm-setup role
          ansible.builtin.include_role:
            name: mock-vm-setup
      rescue:
        - name: set status and message
          ansible.builtin.set_fact:
            status: failed
            message: ansible eda post plan run task encountered and issue. check the controller logs for details
        
- hosts: localhost
  connection: local
  gather_facts: true
  roles:
  - role: run-task-response
    vars:
      status: "{{ status | default('passed') }}"
      message: "{{ message | default('ansible eda post plan run task completed succesfully') }}"