---
- hosts: all
  gather_facts: true
  tasks:
  - name: include terraform state role
    ansible.builtin.include_role:
      name: terraform-state
      apply:
        delegate_to: localhost
        run_once: true

- hosts: "{{ public_dns }}"
  gather_facts: true
  tasks:
    - name: include tasks to execute against target hosts
      block:    
        - name: include mock-vm-setup role
          ansible.builtin.include_role:
            name: mock-vm-setup
      rescue:
        - name: set status and message
          ansible.builtin.set_fact:
            status: failed
            message: ansible eda post plan run task encountered and issue. check the controller logs for details

- hosts: all
  gather_facts: true
  tasks:
  - name: include terraform state role
    ansible.builtin.include_role:
      name: terraform-state
      vars:
        status: "{{ status | default('passed') }}"
      apply:
        delegate_to: localhost
        run_once: true