---
- hosts: all
  gather_facts: false
  roles:
  - role: terraform-state
  - role: run-task-response
    vars:
      status: passed
      message: ansible eda post plan run task completed succesfully
      
    



