---
- hosts: all
  gather_facts: false
  tasks:
  - name: set facts from event data
    ansible.builtin.set_fact:
      access_token: "{{ ansible_eda.event.payload.access_token }}"
      task_result_callback_url: "{{ ansible_eda.event.payload.task_result_callback_url }}"

  - name: output callback details
    ansible.builtin.debug:
      msg: 
      - "{{ access_token }}"
      - "{{ task_result_callback_url }}"

  - name: send run task response
    ansible.builtin.uri:
      url: "{{ task_result_callback_url }}"
      method: POST
      headers:
        Content-Type: application/vnd.api+json
        Authorization: "Bearer {{ access_token }}"
      body:
        data:
          type: task-results
          attributes:
            status: passed
            message: successfully called aap job based on eda event from a run task
            url: "{{ awx_job_id }}"



